services:
  dbm:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    depends_on:
      - mysql-db
      - postgres-db
    tty: true

  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - $PWD/etc/database/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  postgres-db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - $PWD/etc/database/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
