services:
  dbm:
    build: .
    container_name: dbm
    volumes:
      - $PWD:/app
    working_dir: /app
    depends_on:
      - mysql-db
    tty: true

  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - $PWD/etc/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  #TODO: levantar servicio de PostgreSQL también para tests de integración